# Generated by Django 5.2.6 on 2025-09-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reseña'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resennia',
        ),
    ]
